config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  resources :dips
  resources :burgers
  resources :fillings
  resources :sides
  resources :orders
  resources :users
  root 'orders#index'
  get '/logout' => 'application#logout'
end

app/models/burger.rb
# Burger object for orders
class Burger < ActiveRecord::Base
  include Nameable
  include Describable

  # Should only be one burger per order but can't do has one, belongs to many - need to find better solution than this
  has_and_belongs_to_many :orders

  # Prices are required and must be more than 0
  validates :price_single, :price_double,
            presence: true,
            numericality: { greater_than: 0 }
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  before_action :set_burger, only: [:show, :edit, :update, :destroy]

  # GET /burgers
  # GET /burgers.json
  def index
    @burgers = Burger.all
  end

  # GET /burgers/1
  # GET /burgers/1.json
  def show
  end

  # GET /burgers/new
  def new
    @burger = Burger.new
  end

  # GET /burgers/1/edit
  def edit
  end

  # POST /burgers
  # POST /burgers.json
  def create
    @burger = Burger.new(burger_params)

    respond_to do |format|
      if @burger.save
        format.html { redirect_to @burger, notice: 'Burger was successfully created.' }
        format.json { render :show, status: :created, location: @burger }
      else
        format.html { render :new }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /burgers/1
  # PATCH/PUT /burgers/1.json
  def update
    respond_to do |format|
      if @burger.update(burger_params)
        format.html { redirect_to @burger, notice: 'Burger was successfully updated.' }
        format.json { render :show, status: :ok, location: @burger }
      else
        format.html { render :edit }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1
  # DELETE /burgers/1.json
  def destroy
    @burger.destroy
    respond_to do |format|
      format.html { redirect_to burgers_url, notice: 'Burger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_burger
    @burger = Burger.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def burger_params
    params.require(:burger).permit(:name, :description, :spicy, :price_single, :price_double)
  end
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/views/burgers/_form.html.erb
<%= form_for(@burger) do |f| %>
  <% if @burger.errors.any? %>
    <div class="row">
      <div id="error_explanation" class="small-12 medium-10 large-8">
        <h2><%= pluralize(@burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

        <ul>
        <% @burger.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

<div class="row">
  <div class="small-12 medium-10 large-8">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :spicy %><br>
      <%= f.check_box :spicy %>
    </div>
    <div class="field">
      <%= f.label :price_single %><br>
      <%= f.text_field :price_single, :value => (number_with_precision(f.object.price_single, :precision => 2)) %>
    </div>
    <div class="field">
      <%= f.label :price_double %><br>
      <%= f.text_field :price_double, :value => (number_with_precision(f.object.price_double, :precision => 2)) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/burgers/edit.html.erb
<div class="row">
  <div class="small-12 medium-10 large-8">
    <h1>Editing Burger</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="small-12 medium-10 large-8">
    <%= link_to 'Show', @burger, class: 'button radius info' %>
    <%= link_to 'Back', burgers_path, class: 'button radius info' %>
  </div>
</div>

app/views/burgers/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Listing Burgers</h1>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Spicy</th>
          <th>Price (single)</th>
          <th>Price (double)</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @burgers.each do |burger| %>
          <tr>
            <td><%= burger.name %></td>
            <td><%= burger.description %></td>
            <td><%= burger.spicy %></td>
            <td>£<%= number_with_precision(burger.price_single, :precision => 2) %></td>
            <td>£<%= number_with_precision(burger.price_double, :precision => 2) %></td>
            <td><%= link_to 'Show', burger, class: 'button radius tiny info' %></td>
            <td><%= link_to 'Edit', edit_burger_path(burger), class: 'button radius tiny success' %></td>
            <td><%= link_to 'Destroy', burger, method: :delete, class: 'button radius tiny alert', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <%= link_to 'New Burger', new_burger_path, class: 'button radius success' %>
  </div>
</div>

app/views/burgers/new.html.erb
<div class="row">
  <div class="small-12 medium-10 large-8">
    <h1>New Burger</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="small-12 medium-10 large-8">
    <%= link_to 'Back', burgers_path, class: 'button radius info' %>
  </div>
</div>

app/views/burgers/show.html.erb
<div class="row">
  <div class="small-12 medium-10 large-8">
    <p>
      <strong>Name:</strong>
      <%= @burger.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @burger.description %>
    </p>

    <p>
      <strong>Spicy:</strong>
      <%= @burger.spicy %>
    </p>

    <p>
      <strong>Price (single):</strong>
      £<%= number_with_precision(@burger.price_single, :precision => 2) %>
    </p>

    <p>
      <strong>Price (double):</strong>
      £<%= number_with_precision(@burger.price_double, :precision => 2) %>
    </p>
  </div>
</div>
<div class="row">
  <div class="small-12 medium-10 large-8">
    <%= link_to 'Edit', edit_burger_path(@burger), class: 'button radius success' %>
    <%= link_to 'Back', burgers_path, class: 'button radius info' %>
  </div>
</div>