config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  resources :dips
  resources :burgers
  resources :fillings
  resources :sides
  resources :orders
  resources :users
  root 'orders#index'
  get '/logout' => 'application#logout'
end

app/models/filling.rb
# Filling object for orders
class Filling < ActiveRecord::Base
  include Nameable
  include Priceable

  has_and_belongs_to_many :orders
end

app/controllers/fillings_controller.rb
class FillingsController < ApplicationController
  before_action :set_filling, only: [:show, :edit, :update, :destroy]

  # GET /fillings
  # GET /fillings.json
  def index
    @fillings = Filling.all
  end

  # GET /fillings/1
  # GET /fillings/1.json
  def show
  end

  # GET /fillings/new
  def new
    @filling = Filling.new
  end

  # GET /fillings/1/edit
  def edit
  end

  # POST /fillings
  # POST /fillings.json
  def create
    @filling = Filling.new(filling_params)

    respond_to do |format|
      if @filling.save
        format.html { redirect_to @filling, notice: 'Filling was successfully created.' }
        format.json { render :show, status: :created, location: @filling }
      else
        format.html { render :new }
        format.json { render json: @filling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fillings/1
  # PATCH/PUT /fillings/1.json
  def update
    respond_to do |format|
      if @filling.update(filling_params)
        format.html { redirect_to @filling, notice: 'Filling was successfully updated.' }
        format.json { render :show, status: :ok, location: @filling }
      else
        format.html { render :edit }
        format.json { render json: @filling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fillings/1
  # DELETE /fillings/1.json
  def destroy
    @filling.destroy
    respond_to do |format|
      format.html { redirect_to fillings_url, notice: 'Filling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_filling
    @filling = Filling.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def filling_params
    params.require(:filling).permit(:name, :spicy, :price)
  end
end

app/helpers/fillings_helper.rb
module FillingsHelper
end

app/views/fillings/_form.html.erb
<%= form_for(@filling) do |f| %>
  <% if @filling.errors.any? %>
    <div class="row">
      <div id="error_explanation" class="small-12 medium-10 large-8">
        <h2><%= pluralize(@filling.errors.count, "error") %> prohibited this filling from being saved:</h2>

        <ul>
        <% @filling.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

<div class="row">
  <div class="small-12 medium-10 large-8">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :spicy %><br>
      <%= f.check_box :spicy %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price, :value => (number_with_precision(f.object.price, :precision => 2)) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/fillings/edit.html.erb
<div class="row">
  <div class="small-12 medium-10 large-8">
    <h1>Editing Extra Filling</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="small-12 medium-10 large-8">
    <%= link_to 'Show', @filling, class: 'button radius info' %>
    <%= link_to 'Back', fillings_path, class: 'button radius info' %>
  </div>
</div>

app/views/fillings/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Listing Extra Fillings</h1>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Spicy</th>
          <th>Price</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @fillings.each do |filling| %>
          <tr>
            <td><%= filling.name %></td>
            <td><%= filling.spicy %></td>
            <td>£<%= number_with_precision(filling.price, :precision => 2) %></td>
            <td><%= link_to 'Show', filling, class: 'button radius tiny info' %></td>
            <td><%= link_to 'Edit', edit_filling_path(filling), class: 'button radius tiny success' %></td>
            <td><%= link_to 'Destroy', filling, method: :delete, class: 'button radius tiny alert', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <%= link_to 'New Extra Filling', new_filling_path, class: 'button radius success' %>
  </div>
</div>

app/views/fillings/new.html.erb
<div class="row">
  <div class="small-12 medium-10 large-8">
    <h1>New Extra Filling</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="small-12 medium-10 large-8">
    <%= link_to 'Back', fillings_path, class: 'button radius info' %>
  </div>
</div>

app/views/fillings/show.html.erb
<div class="row">
  <div class="small-12 medium-10 large-8">
    <p>
      <strong>Name:</strong>
      <%= @filling.name %>
    </p>

    <p>
      <strong>Spicy:</strong>
      <%= @filling.spicy %>
    </p>

    <p>
      <strong>Price:</strong>
      £<%= number_with_precision(@filling.price, :precision => 2) %>
    </p>
  </div>
</div>
<div class="row">
  <div class="small-12 medium-10 large-8">
    <%= link_to 'Edit', edit_filling_path(@filling), class: 'button radius success' %>
    <%= link_to 'Back', fillings_path, class: 'button radius info' %>
  </div>
</div>