config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  resources :dips
  resources :burgers
  resources :fillings
  resources :sides
  resources :orders
  resources :users
  root 'orders#index'
  get '/logout' => 'application#logout'
end

app/models/side.rb
# Side object for order
class Side < ActiveRecord::Base
  include Nameable
  include Describable
  include Priceable

  has_and_belongs_to_many :orders
end

app/controllers/sides_controller.rb
class SidesController < ApplicationController
  before_action :set_side, only: [:show, :edit, :update, :destroy]

  # GET /sides
  # GET /sides.json
  def index
    @sides = Side.all
  end

  # GET /sides/1
  # GET /sides/1.json
  def show
  end

  # GET /sides/new
  def new
    @side = Side.new
  end

  # GET /sides/1/edit
  def edit
  end

  # POST /sides
  # POST /sides.json
  def create
    @side = Side.new(side_params)

    respond_to do |format|
      if @side.save
        format.html { redirect_to @side, notice: 'Side was successfully created.' }
        format.json { render :show, status: :created, location: @side }
      else
        format.html { render :new }
        format.json { render json: @side.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sides/1
  # PATCH/PUT /sides/1.json
  def update
    respond_to do |format|
      if @side.update(side_params)
        format.html { redirect_to @side, notice: 'Side was successfully updated.' }
        format.json { render :show, status: :ok, location: @side }
      else
        format.html { render :edit }
        format.json { render json: @side.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sides/1
  # DELETE /sides/1.json
  def destroy
    @side.destroy
    respond_to do |format|
      format.html { redirect_to sides_url, notice: 'Side was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_side
    @side = Side.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def side_params
    params.require(:side).permit(:name, :description, :spicy, :price)
  end
end

app/helpers/sides_helper.rb
module SidesHelper
end

app/views/sides/_form.html.erb
<%= form_for(@side) do |f| %>
  <% if @side.errors.any? %>
    <div class="row">
      <div id="error_explanation" class="small-12 medium-10 large-8">
        <h2><%= pluralize(@side.errors.count, "error") %> prohibited this side from being saved:</h2>

        <ul>
        <% @side.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

<div class="row">
  <div class="small-12 medium-10 large-8">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :spicy %><br>
      <%= f.check_box :spicy %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price, :value => (number_with_precision(f.object.price, :precision => 2)) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/sides/edit.html.erb
<div class="row">
  <div class="small-12 medium-10 large-8">
    <h1>Editing Side</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="small-12 medium-10 large-8">
    <%= link_to 'Show', @side, class: 'button radius info' %>
    <%= link_to 'Back', sides_path, class: 'button radius info' %>
  </div>
</div>

app/views/sides/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Listing Sides</h1>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Spicy</th>
          <th>Price</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @sides.each do |side| %>
          <tr>
            <td><%= side.name %></td>
            <td><%= side.description %></td>
            <td><%= side.spicy %></td>
            <td>£<%= number_with_precision(side.price, :precision => 2) %></td>
            <td><%= link_to 'Show', side, class: 'button radius tiny info' %></td>
            <td><%= link_to 'Edit', edit_side_path(side), class: 'button radius tiny success' %></td>
            <td><%= link_to 'Destroy', side, method: :delete, class: 'button radius tiny alert', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <%= link_to 'New Side', new_side_path, class: 'button radius success' %>
  </div>
</div>

app/views/sides/new.html.erb
<div class="row">
  <div class="small-12 medium-10 large-8">
    <h1>New Side</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="small-12 medium-10 large-8">
    <%= link_to 'Back', sides_path, class: 'button radius info' %>
  </div>
</div>

app/views/sides/show.html.erb
<div class="row">
  <div class="small-12 medium-10 large-8">
    <p>
      <strong>Name:</strong>
      <%= @side.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @side.description %>
    </p>

    <p>
      <strong>Spicy:</strong>
      <%= @side.spicy %>
    </p>

    <p>
      <strong>Price:</strong>
      £<%= number_with_precision(@side.price, :precision => 2) %>
    </p>
  </div>
</div>
<div class="row">
  <div class="small-12 medium-10 large-8">
    <%= link_to 'Edit', edit_side_path(@side), class: 'button radius success' %>
    <%= link_to 'Back', sides_path, class: 'button radius info' %>
  </div>
</div>